#include<linux/init.h>
#include<linux/module.h>
#include<linux/version.h>
#include<linux/kernel.h>
#include<linux/types.h>
#include<linux/fs.h>
#include<linux/kdev_t.h>
#include<linux/cdev.h>
#include<linux/random.h>
#include <linux/uaccess.h>
#include "adcdev.h"

#define SUCCESS 0


static dev_t myadc;
static struct cdev c_dev;
static struct class *cls;
static uint16_t c = 0;
static char al = 'r';
static int Device_Open = 0;
uint16_t randomgenerator(void);

//called when user opens device
static int adc_open(struct inode *i,struct file *f){
		if (Device_Open)
        		return -EBUSY;

    		Device_Open++;
		return SUCCESS;
	}

//called when user closes device
static int adc_close(struct inode *i,struct file *f){
		Device_Open--;
		return SUCCESS;

	}

//called when we try to read data from adc
static ssize_t adc_read(struct file *f, char __user *buf, size_t len, loff_t *off){
    	int missingbits;
    	uint16_t randno;
    	randno = randomgenerator();
	printk(KERN_INFO " random number generated by driver is %d",randno);
	if(al == 'l'){									// for left alignment
			randno = randno * 16;				// one bit left shift is equal to *2 so 4 bit leftshift is *16
			}
	printk(KERN_INFO "Current channel being used is %d and data alignment %c ",c,al);
    	missingbits = copy_to_user(buf,&randno,sizeof(randno));
    	if(missingbits!=0){
    printk(KERN_INFO "Failed to copy %d byte(s) to the userspace ",missingbits);
    }
		return sizeof(randno);

	}

// adc_ioctl called when user make ioctl system call
long adc_ioctl(struct file *file,unsigned int ioctl_num,unsigned long ioctl_param){

                switch(ioctl_num)
{
                  case SEL_CHANNEL:
			c = ioctl_param;
			//printk(KERN_INFO "current request code from channel is %u",ioctl_num);
                    	printk(KERN_INFO "CHANNEL SELECTED IS %d",c);
			break;

                  case SEL_ALIGNMENT:
                    	al = (char)ioctl_param;
			//printk(KERN_INFO "current request code from alignment is %u",ioctl_num);
                    	printk(KERN_INFO "ALLIGNMENT SELECTED - %c",al);
			break;

                  case SEL_CONV:
                    	al = ioctl_param;

			//printk(KERN_INFO "current request code for conversion is %u",ioctl_num);
                    	printk(KERN_INFO "CONVERSION SELECTED - %c",al);
			break;
                }
              return SUCCESS;
  }

uint16_t randomgenerator(void){
    unsigned int num;
    get_random_bytes(&num, 2);
    num%=4095;
    return (uint16_t)num;
  }
  
  //file operation structures

static struct file_operations fops =
					{
					.owner = THIS_MODULE,
					.open = adc_open,
					.release = adc_close,
                                        .unlocked_ioctl = adc_ioctl,
					.read = adc_read
					};

// initialization functions

__init int adcdriver_init(void){
	// Step 1: Allocation of major and minor numbers.
	if(alloc_chrdev_region(&myadc,0,5,"Embedded Anurag")<0){
		return -1;
	}
	printk(KERN_INFO "<major , minor>:<%d,%d>\n",MAJOR(myadc),MINOR(myadc));// to see the alloted major and minor no.

	// Step 2: Creation of device file.
	if((cls=class_create(THIS_MODULE,"adcclass"))==NULL){
		printk(KERN_INFO "class not created");
			unregister_chrdev_region(myadc,1);
			return -1;
	}
	
	// creating device
	if((device_create(cls,NULL,myadc,NULL,"adc-dev"))==NULL){
		printk(KERN_INFO "device not created");
			class_destroy(cls);
			unregister_chrdev_region(myadc,1);
			return -1;
	}
	//Step 3: Link fops and cdev to device node;
	cdev_init(&c_dev,&fops);
	//making the driver live
	if(cdev_add(&c_dev,myadc, 1)==-1){
		device_destroy(cls,myadc);
		class_destroy(cls);
		unregister_chrdev_region(myadc,1);
			printk(KERN_INFO "driver not live");
		return -1;
	}
	printk(KERN_INFO "Insertion done ");
	return SUCCESS;
}


__exit void adcdriver_exit(void){
	cdev_del(&c_dev);
	device_destroy(cls,myadc);
	class_destroy(cls);
	printk(KERN_INFO "entered in exit routine");
	unregister_chrdev_region(myadc,3);
	printk(KERN_INFO "Deleted successfully ");
}


module_init(adcdriver_init);
module_exit(adcdriver_exit);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("12 bit 8 channel adc");
MODULE_AUTHOR("Anurag Dobriyal <h20210346@pilani.bits-pilani.ac.in>");
